window:
  size:
    - 480
    - 854
  background_color:
    - 4
    - 4
    - 16
    - 255
  borderless: false
ball:
  color:
    - 154
    - 190
    - 170
    - 0
  highlight_color:
    - 64
    - 255
    - 64
    - 255
  radius: 10
  margin: 5
  highlight_frames: 10
  image: frog_transparent.png
